name: azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101'

      - name: dotnet build
        shell: bash
        run: |
          pushd .
          dotnet publish Functions/Functions.csproj --configuration Release --output ./output
          popd

      - name: publish
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: azdo2gh
          package: './output'